name: CI
on:
  push:
    branches:
      - 'main'
  pull_request:
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        config:
        # [Python version, tox env]
        - ["2.7",  "py27-plone52", "ubuntu-20.04"]
        - ["3.8",  "py38-plone52", "ubuntu-latest"]
        - ["3.8",  "py38-plone60", "ubuntu-latest"]
        - ["3.9",  "py39-plone60", "ubuntu-latest"]
        - ["3.10",  "py310-plone60", "ubuntu-latest"]
        - ["3.11",  "py311-plone60", "ubuntu-latest"]
    runs-on: ${{ matrix.config[2] }}
    name: ${{ matrix.config[1] }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config[0] }}
    - name: Pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.config[0] }}-${{ hashFiles('setup.*', 'tox.ini') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.config[0] }}-
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Prepare buildout egg cache
      run: |
        mkdir ~/.buildout
        echo "[buildout]" >> ~/.buildout/default.cfg
        echo "eggs-directory = ~/eggs" >> ~/.buildout/default.cfg
    - name: Cache eggs
      uses: actions/cache@v3
      with:
        path: ~/eggs
        key: ${{ runner.os }}-eggs-${{ matrix.config[0] }}-${{ matrix.config[1] }}-${{ hashFiles('*cfg') }}
        restore-keys: |
          ${{ runner.os }}-eggs-${{ matrix.config[0] }}-${{ matrix.config[1] }}-
          ${{ runner.os }}-eggs-${{ matrix.config[0] }}-
    - name: Test
      run: tox -e ${{ matrix.config[1] }}
