name: CI
on:
  push:
    branches:
      - 'main'
  pull_request:
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: true
    runs-on: ubuntu-20.04
    container:
      image: python:2.7.18-buster
    name: py27-plone52
    steps:
    - uses: actions/checkout@v3
    - name: Pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-2.7-${{ hashFiles('setup.*', 'tox.ini') }}
        restore-keys: |
          ${{ runner.os }}-pip-2.7-
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Prepare buildout egg cache
      run: |
        mkdir ~/.buildout
        echo "[buildout]" >> ~/.buildout/default.cfg
        echo "eggs-directory = ~/eggs" >> ~/.buildout/default.cfg
    - name: Cache eggs
      uses: actions/cache@v3
      with:
        path: ~/eggs
        key: ${{ runner.os }}-eggs-2.7-py27-plone52-${{ hashFiles('*cfg') }}
        restore-keys: |
          ${{ runner.os }}-eggs-2.7-py27-plone52-
          ${{ runner.os }}-eggs-2.7-
    - name: Test
      run: tox -e py27-plone52
